# Generated by Django 2.2 on 2020-11-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.EmailField(default='Scarface@gmail.com', max_length=254),
        ),
    ]
