# Generated by Django 2.2 on 2020-11-11 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0002_question_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='Scarface', max_length=30),
        ),
    ]
