# Generated by Django 2.2 on 2020-11-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20201111_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
