# Generated by Django 2.2 on 2020-11-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20201111_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='lecture',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
