"""
Django settings for the_market project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
from django.contrib.messages import constants as messages

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@%-@8oq%$0lmkk*iv*^(gb0ueh6ob%h^b5ezkw-_=)v-3=k_+q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='agboemmanuel002@gmail.com'
EMAIL_HOST_PASSWORD='08032884565'
EMAIL_PORT=587
EMAIL_USER_TLS=True
DEFAULT_FROM_EMAIL='agboemmanuel002@gmail.com'
# DEFAULT_TO_EMAIL='maron15686@unknmail.com'
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  
# MAILER_EMAIL_BACKEND = EMAIL_BACKEND  
# EMAIL_HOST = 'your_mail_server'  
# EMAIL_HOST_PASSWORD = 'your_password'  
# EMAIL_HOST_USER = 'your_email'  
# EMAIL_PORT = 465  
# EMAIL_USE_SSL = True  
# DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

ADMINS = (
       ('agboemmanuel002@gmail.com'),
    )
MANAGERS = ADMINS
# Application definition

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'Profile',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'programs',
    'cart',
    'lecture',
    'crispy_forms',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]





ROOT_URLCONF = 'the_market.urls'

AUTH_USER_MODEL = "Profile.CustomUser"

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [r'C:\host\cfehome\src\templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'the_market.wsgi.application'

AUTHENTICATION_BACKENDS = (
        'django.contrib.auth.backends.RemoteUserBackend',
        'django.contrib.auth.backends.ModelBackend',
)
# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


#messages


MESSAGE_TAGS = {
    messages.ERROR: 'danger',
}

# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT= os.path.join(BASE_DIR, 'media/')
STATIC_ROOT= os.path.join(BASE_DIR, 'static/')
MEDIA_URL= "/media/"
LOGOUT_REDIRECT_URL="/accounts/login"
LOGIN_REDIRECT_URL="/"
# 
STRIPE_PUBLISHABLE_KEY = '<pk_test_51HkeSVEvd46hirUlsed5mAWraxuYU1pREvgZc4wTEsjBdECAkh8A4gY2mVyJWCo6rLrALbDUUGX0nqJTYR3dVJlG002VvYhtMf>'
STRIPE_SECRET_KEY = '<sk_test_51HkeSVEvd46hirUl96Z1PD3MTbPNpsu8iwK8tCJupSbN77DDBQwJUPpgWSn3DtNQ2E16SBpD3eOdVq1W1EhxSWQM00OLerrO7R>'
CRISPY_TEMPLATE_PACK = 'bootstrap3'