# Generated by Django 2.2 on 2020-11-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registered_Course',
            field=models.ManyToManyField(blank=True, to='programs.Programs'),
        ),
    ]
