# Generated by Django 2.2 on 2020-11-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_instructors_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='photo',
            field=models.ImageField(null=True, upload_to='gallery'),
        ),
    ]
