# Generated by Django 3.0.8 on 2020-11-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.BooleanField(default=False)),
                ('christmas', models.BooleanField(default=False)),
                ('new_year', models.BooleanField(default=False)),
                ('easter', models.BooleanField(default=False)),
            ],
        ),
    ]
