# Generated by Django 3.0.8 on 2020-11-20 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201112_1048'),
        ('cart', '0002_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Profile'),
        ),
    ]
