# Generated by Django 3.0.8 on 2020-11-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_free_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Free',
        ),
    ]
