# Generated by Django 3.0.8 on 2020-11-20 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201112_1048'),
        ('cart', '0004_delete_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Free',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free', models.BooleanField(default=False)),
                ('christmas', models.BooleanField(default=False)),
                ('new_year', models.BooleanField(default=False)),
                ('easter', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Profile.Profile')),
            ],
        ),
    ]
