# Generated by Django 3.0.8 on 2020-11-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free',
            name='owner',
        ),
    ]
