# Generated by Django 3.0.8 on 2020-11-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_free_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='free',
            name='christmas',
        ),
        migrations.RemoveField(
            model_name='free',
            name='easter',
        ),
        migrations.RemoveField(
            model_name='free',
            name='free',
        ),
        migrations.RemoveField(
            model_name='free',
            name='new_year',
        ),
        migrations.AddField(
            model_name='free',
            name='promo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
