# Generated by Django 3.0.8 on 2020-11-23 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20201122_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='is_On',
            field=models.BooleanField(default=False),
        ),
    ]
