# Generated by Django 3.0.8 on 2020-11-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_free_is_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='free',
            name='christmas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='free',
            name='easter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='free',
            name='new_year',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='free',
            name='thanksgiving',
            field=models.BooleanField(default=False),
        ),
    ]
